### ISSUE TITLE
Blue box around app on Desktop

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/EIC-Mobile#19]
On Desktop, I get a blue box around the whole app when I start interacting with the globe.

Like an active state.

When I click on the chart or another element of the bottom panel, the box goes away.

![image](https://github.com/user-attachments/assets/d2033510-dd3b-48b2-b7d2-7d1d81bdbb93)

**Comment by dzole0311** [comment]
Closing as implemented.
