### ISSUE TITLE
Selection of option on scenario overlay should close the overlay

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/EIC-Mobile#23]
When the user selects a scenario on the modal/overlay, they currently have to click on a small cross or outside the text (or hit escape on Desktop) to close the overlay.

Instead, the overlay should close as soon as an option is selected.

Perhaps that behavior should also extend to selecting the units on the parameter selection? 🤔 

![image](https://github.com/user-attachments/assets/14a8eaab-7c9a-4b55-ab2c-4b0fede79829)

**Comment by faustoperez** [comment]
> Perhaps that behavior should also extend to selecting the units on the parameter selection

Thanks for capturing this on a ticket @j08lue. Yes, for the sake of consistency let's extend it to the temperature modal 👍
