### ISSUE TITLE
Add loading spinner while the front-end is querying the ImageService

### ISSUE THREAD

**Issue by dzole0311** [NASA-IMPACT/EIC-Mobile#31]
Add a loading spinner in the chart in-between requests to the ImageService.

**Comment by faustoperez** [comment]
Here are some tentative designs for this:

Link to Figma 👉 https://www.figma.com/design/2Vd0SDhFOTBJaYioJPr0Ei/Earth.gov?node-id=1456-768&t=ZOn1yzGCLAf4jJgM-1

---

<img width="1440" alt="Loading states 1" src="https://github.com/user-attachments/assets/513609cc-646d-4f26-9e80-1ee4948132e1">

- [ ] The buttons on the should be diabled (opacity 0.5) and the chart replaced with a spinner message
- [ ] The spinning icon uses the primary color and it's on the Phosphor library 

---

<img width="1440" alt="Loading states 2" src="https://github.com/user-attachments/assets/bafdc857-feae-4d13-9835-5c472257c653">

- [ ] If users click on the ocean, the map flies to the last valid land location without zooming the map and informs the user about what's happening.

**Comment by j08lue** [comment]
Done.
