### ISSUE TITLE
Use animated pulsating marker for time series sample location

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/EIC-Mobile#33]
We need to make a change to the sample location marker on the globe, so it looks less like a buffer (we are only sampling point values, not zonal statistics).

## Design

The marker needs to draw attention on a background with busy colors, invite users to move it, and have affordance for touch devices.

Design proposal: 48x48px target crosshair, animated pulsating dot

![image](https://github.com/user-attachments/assets/f75841d7-6c69-4994-a1a9-2f3c48bcc80c)

## Implementation

1. Are animated GIFs or a CSS/SVG solution currently possible? https://community.esri.com/t5/arcgis-javascript-maps-sdk-questions/animated-picturemarkersymbol/td-p/419275
2. Or do we need to go WebGL? https://developers.arcgis.com/javascript/latest/sample-code/custom-gl-visuals/

The solution needs to work well on mobile.

**Comment by j08lue** [comment]
Authoritative info from ESRI:

- WebGL with a CustomRender node seems to be the only viable option with the current version
   - https://developers.arcgis.com/javascript/latest/sample-code/custom-render-node-windmills/
   - https://developers.arcgis.com/javascript/latest/sample-code/custom-gl-visuals/
- Animated gifs & pngs are currently supported in 2D maps, but not 3D maps
- SVG animations are not supported in either 2D or 3D yet
- A 2D animated symbol API is in beta and coming very soon for the JS SDK, 3D support will be further off

**Comment by ycabon** [comment]
Hi, I'm a developer on the JS SDK. Your design looks great!

While the API doesn't provide out of the box animation options, it's possible to do some animations on `Graphic` objects by animating their `symbol` property. Here are couple of examples:
 - [using plain JS](https://codepen.io/ycabon/pen/MWNjBjr) 
 - [or using GSAP animation library](https://codepen.io/ycabon/pen/qBeayrv) - the [library](https://gsap.com/) provides a lot of options.

**Comment by j08lue** [comment]
We can revisit this in case someone wants us to revisit markers.
