### ISSUE TITLE
Add Digital Analytics Program (DAP) header

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/EIC-Mobile#38]
From @amarouane-ABDELHAK:

> Since https://earth.gov/mobile-climate-mapper/ is under a federal website I think we should add Digital Analytics Program (DAP) header before someone asks us to.
> 
> More info at https://digital.gov/guides/dap/get-started-with-dap/

**Comment by j08lue** [comment]
We would probably use the same info as for Earth.gov?

https://github.com/NASA-IMPACT/veda-config-eic/blob/4ba10c067de5429954ea8353edb02190b87ca1a0/.env#L28-L29

**Comment by amarouane-ABDELHAK** [comment]
These were the requirements to install DAP for earth.gov
```html
Implementing the DAP script block:
<script async type="text/javascript" src="[https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=NASA&subagency=](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdap.digitalgov.gov%2FUniversal-Federated-Analytics-Min.js%3Fagency%3DNASA%26subagency%3DGSFC&data=05%7C02%7Cnatasha.r.pinol%40nasa.gov%7C2e7990797e3f4f4abc9308dc2cabb6da%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638434363219622130%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=s8hnZfUhyK87dNIK0mCgoACaocI2%2Bdvdk%2Ba21z02m9s%3D&reserved=0)Center" id="_fed_an_ua_tag"></script> 
The script block above must be inserted in the <head> of all public-facing pages on your site. 
The best location for the script block is directly before the closing </head>. 
Do not change “agency=NASA” to any other value.
Replace Center with your NASA Center’s acronym (AFRC, GSFC, etc.). Use HQ for websites managed out of Agency-level offices. 
The above example is the minimum required script block. Additional DAP parameters (e.g., “yt=true”, “dclink=true”) may be added at the website owner’s discretion. 
```
Please follow the instructions and examples in GSA’s [DAP Quick Guide](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdigital-analytics-program%2Fgov-wide-code%2Fblob%2Fmaster%2Fdocumentation%2FGSA%2520DAP%25204.1%2520-%2520Quick%2520Guide.pdf&data=05%7C02%7Cnatasha.r.pinol%40nasa.gov%7C2e7990797e3f4f4abc9308dc2cabb6da%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638434363219631314%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=nQj8oSLneFFaNygqwHEWWHYeljLaCwv9GgYpE%2FAwrRQ%3D&reserved=0) starting on page 7.

**Comment by amarouane-ABDELHAK** [comment]
I think we can just add it to index.html before ```</head> ```

**Comment by j08lue** [comment]
This has not yet happened, right?

**Comment by amarouane-ABDELHAK** [comment]
Not yet, waiting for a green light from @brianmfreitag ?

**Comment by freitagb** [comment]
@amarouane-ABDELHAK sorry i missed this. Can we tag up on this quickly tomorrow?

**Comment by amarouane-ABDELHAK** [comment]
@brianmfreitag and I had a tagup, and we've decided to use `agency=NASA&subagency=HQ`. I'll be submitting a PR shortly. We need to ensure that the DAP script is only added when the app is served on .gov domains, and not for Netlify previews.

**Comment by amarouane-ABDELHAK** [comment]
PR created https://github.com/NASA-IMPACT/EIC-Mobile/pull/68

**Comment by amarouane-ABDELHAK** [comment]
The DAP script is appearing in the app when the variable ADD_DAP_SCRIPT  is set to "true"
<img width="1704" alt="image" src="https://github.com/user-attachments/assets/21efec75-7917-4831-b2d3-79a574733af4">
