### ISSUE TITLE
Add auth to timeseries requests

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/EIC-Mobile#47]
Timeseries requests will need to authenticate with an access token with limited lifetime.

Tokens can be requested from a service, using username and password. The service currently does not implement OAuth 2.0 flows, e.g. refresh tokens.

We therefore follow a very simple implementation for now, where

1. A scheduled process generates a token on a regular interval for the application and stores it in the application environment / config
2. The application picks up the token from its environment and adds it to timeseries API requests
3. Repeat

In the future, we could consider other ways like refresh tokens, one token per user session, etc.

## Resources

This is a dev / test endpoint that requires auth:

https://gis.earthdata.nasa.gov/eictester/rest/services/tasmax_yearly_median/ImageServer

**Comment by j08lue** [comment]
## Python example code

This is how you can request a token:

```python
import requests

token_url = "https://gis.earthdata.nasa.gov/eictester/tokens/generateToken?f=json"

data = {
    "username": "username",
    "password": "password",
    "client": "requestip",
    #"client": "referer",
    #"referer": "my-referer.com",
    "expiration": 1440  # minutes ; docs say max lifetime is 24 hours
}
response = requests.post(token_url, data=data)
response.raise_for_status()
token = response.json().get("token")
if token is None:
  raise RuntimeError(response.content)
```

and this how you apply it in a request:

```python
data_url = "https://gis.earthdata.nasa.gov/eictester/rest/services/tasmax_yearly_median/ImageServer/getSamples?geometry=-69.534990,45.532910&geometryType=esriGeometryPoint&returnFirstValueOnly=false&f=json&time=1950-01-31T00%3A00%3A00.000Z%2C2100-12-31T23%3A59%3A59.000Z"
header = {
    "Host": "gis.earthdata.nasa.gov",
    "Authorization": f"Bearer {token}",
    #"referer": "my-referer.com"
}
response = requests.get(data_url, headers=header)
response.raise_for_status()
content = response.content.decode("utf-8")
print(content)
```

## Docs

A POST request is made to get an application token.

Endpoint Notes

1. In this example, `"client": "requestip"` is used, but for an app, instead `"client": "referer"` and `"referer": "(app host)"` would be used. See the documentation link below. HTTPS is used to safely transfer credentials.
2. The max token expiration is 24 hours (1440 minutes) The server may be configured for up to 14 days (20,160 minutes) if needed.
3. The referer field should be updated to include the URL making the request.
4. The endpoint returns a token and expires with expires being milliseconds since Jan 1st 1970
5. For an app token, replace `"client": "ip"` with `"client": "referer"`

References

1. For more information on the endpoint: https://gis.earthdata.nasa.gov/eictester/help/en/rest/enterprise-administration/server/generatetoken/
2. For more informaiton on token expiration: https://enterprise.arcgis.com/en/portal/latest/administer/windows/specify-the-default-token-expiration-time.htm

**Comment by amarouane-ABDELHAK** [comment]
Looks like we can generate a token with a longer lifespan:
```python
data = {
    "username": username,
    "password": password,
    "client": "referer",
    "referer": "https://earthdata.gov",
    "expiration": 14400
}
token_response = requests.post(token_url, data=data)
token = token_response.json().get("token")
if token is None:
    print(token_response.status_code, token_response.content)
header = {
    "Referer": "https://earthdata.gov",
    "Authorization": f"Bearer {token}"
}
token_response.json()
{'token': '_TOKENGENERATED..',
 'expires': 1728914650029}
```

**Comment by amarouane-ABDELHAK** [comment]
I will set up a job in GitHub Actions to generate a token (valid for 10 days) that will be stored in an environment variable GIS_TOKEN. This variable will be used to build the app. Before the token expires, GitHub Actions will run on a cron schedule to refresh the token (every 7 days), build the app with the newly generated token, and then push it to production. In case of failure in building or generating the token, we will receive Slack and email notifications.

**Comment by dzole0311** [comment]
> I will set up a job in GitHub Actions to generate a token (valid for 10 days) that will be stored in an environment variable GIS_TOKEN. This variable will be used to build the app. Before the token expires, GitHub Actions will run on a cron schedule to refresh the token (every 7 days), build the app with the newly generated token, and then push it to production. In case of failure in building or generating the token, we will receive Slack and email notifications.

@amarouane-ABDELHAK I've adjusted the request to consider a GIS_TOKEN env variable in this PR: https://github.com/NASA-IMPACT/EIC-Mobile/pull/51/files#diff-900b2578438f0dfc98ec3ea732e1fed0aba5c31be5f21201c4311f0737c76fa0R38

The request should work once you add the env variable with the token on GitHub.

**Comment by amarouane-ABDELHAK** [comment]
I tried the token locally but it didn't work. I have tried the same token generated from the notebook and tried it with the app locally using address-request branch 
![Screenshot 2024-10-04 at 4 40 34 PM](https://github.com/user-attachments/assets/eb7fec99-ff40-4d8d-82c7-2bbae1205266)
![Screenshot 2024-10-04 at 4 42 22 PM](https://github.com/user-attachments/assets/0ac9387b-c5a8-4b0f-b93a-2e7ccb570dfa)

@brianmfreitag we probably need to talk to gis folks Monday

**Comment by j08lue** [comment]
Done.
