### ISSUE TITLE
Pick a Greenhouse Gas Emissions Scenario 'more info' link invalid: 404

### ISSUE THREAD

**Issue by lwschwizer** [NASA-IMPACT/EIC-Mobile#72]
On the "Pick a Greenhouse Gas Emissions Scenario" pop up, the link at the bottom is invalid, throws a 404. Link text is "Learn more at https://earth.gov/stories/si_nmnh (not sure what the correct link is)

**Comment by freitagb** [comment]
The only place we really talk about the emissions scenarios is in the [CMIP6 data page](https://earth.gov/data-catalog/cmip6-climdex-tasmax-yearly-median) which is already linked under the variables pop up. The [original link](https://github.com/NASA-IMPACT/veda-config-eic/pull/138/files#diff-4ae205b7ca069443279588ca8f2aeaf6c605ede974eec70267924c6e7b896dfd) pointed to information about the exhibit which was replaced with the [smithsonian site ](https://naturalhistory.si.edu/NASA-EIC) which does not seem to have information relevant to the GHG emissions scenarios. My two cents is we could either link to the data page in the emissions scenario pop up or remove the `Learn More` altogether and I'm leaning toward removing the `Learn More` altogether.

**Comment by lwschwizer** [comment]
I agree with removing. The data page does not have an extensive description of scenarios so if that is not easily found/provided, recommend removing it.
